/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.screens;
import DBConnection.DBConnection;
import com.baseActions.EmpActions;
import com.baseActions.EmpDetails;
import com.baseActions.MotorPH_String;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import javax.swing.JFrame;
/**
 *
 * @author JD Morales
 */
public class JFrameEmpInfo extends javax.swing.JFrame {

    private int id =0;
    private EmpDetails empDetails;
    private Iterable<EmpDetails> filteredList;
        
    public JFrameEmpInfo() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setResizable(false);
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelHeader = new javax.swing.JPanel();
        labelCompany = new java.awt.Label();
        labelLogo = new javax.swing.JLabel();
        jPanelFooter = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanelNavHome = new javax.swing.JPanel();
        jButtonLeaveApp = new javax.swing.JButton();
        jButtonHome = new javax.swing.JButton();
        jButtonLogout = new javax.swing.JButton();
        jButtonTimesheet = new javax.swing.JButton();
        jButtonEmpInfo = new javax.swing.JButton();
        jButtonPayroll1 = new javax.swing.JButton();
        jPanelEmpProfile = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1LastName = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField2FirstName = new javax.swing.JTextField();
        jDateChooser1Birthday = new com.toedter.calendar.JDateChooser();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextField3Email = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jComboBox1Designation = new javax.swing.JComboBox<>();
        jButton8AddEmp = new javax.swing.JButton();
        jButton9Update = new javax.swing.JButton();
        jButton11Clear = new javax.swing.JButton();
        jLabel3EmpNo = new javax.swing.JLabel();
        jTextFieldEmpNo = new javax.swing.JTextField();
        jLabel3Supervisor = new javax.swing.JLabel();
        jTextFieldSupervisor = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabelPhoneNo = new javax.swing.JLabel();
        jTextFieldPhoneNo = new javax.swing.JTextField();
        jLabelSSS = new javax.swing.JLabel();
        jTextFieldSSS = new javax.swing.JTextField();
        jLabelPhilHealth = new javax.swing.JLabel();
        jTextFieldPhilHealth = new javax.swing.JTextField();
        jLabelStatus = new javax.swing.JLabel();
        jTextFieldStatus = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaAddress = new javax.swing.JTextArea();
        jLabelTIN = new javax.swing.JLabel();
        jTextFieldTIN = new javax.swing.JTextField();
        jLabelPagIbig = new javax.swing.JLabel();
        jTextFieldPAGIBIG = new javax.swing.JTextField();
        jButtonDelete = new javax.swing.JButton();
        jLabel3Position = new javax.swing.JLabel();
        jTextFieldPosition = new javax.swing.JTextField();
        jPanelSearch = new javax.swing.JPanel();
        jLabel1Search = new javax.swing.JLabel();
        jTextField1Search = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonViewInformation = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1080, 720));

        jPanelHeader.setBackground(new java.awt.Color(99, 93, 255));

        labelCompany.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        labelCompany.setForeground(new java.awt.Color(255, 255, 255));
        labelCompany.setText("MotorPH");

        labelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LOGO_icon.png"))); // NOI18N
        labelLogo.setText("jLabel1");
        labelLogo.setMaximumSize(new java.awt.Dimension(172, 119));
        labelLogo.setMinimumSize(new java.awt.Dimension(172, 119));
        labelLogo.setPreferredSize(new java.awt.Dimension(172, 192));

        javax.swing.GroupLayout jPanelHeaderLayout = new javax.swing.GroupLayout(jPanelHeader);
        jPanelHeader.setLayout(jPanelHeaderLayout);
        jPanelHeaderLayout.setHorizontalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelHeaderLayout.setVerticalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addGroup(jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelHeaderLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelHeaderLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(labelCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelFooter.setBackground(new java.awt.Color(99, 93, 255));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Office Hours: 8:00AM - 5:00PM");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Office Address: 5th Flr., The World Center #330 Sen. Gil Puyat Ave., Makati City, Manila, Philippines");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Office Phone Number: +63-2-754-7000");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Office Email: support@motorph.com");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Group 1");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Section : A1101");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("MO-IT103 - Computer Programming 2");

        javax.swing.GroupLayout jPanelFooterLayout = new javax.swing.GroupLayout(jPanelFooter);
        jPanelFooter.setLayout(jPanelFooterLayout);
        jPanelFooterLayout.setHorizontalGroup(
            jPanelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelFooterLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addGroup(jPanelFooterLayout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(396, 396, 396)
                            .addComponent(jLabel11))
                        .addGroup(jPanelFooterLayout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(687, 687, 687)
                            .addComponent(jLabel21))
                        .addGroup(jPanelFooterLayout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(574, 574, 574)
                            .addComponent(jLabel18)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelFooterLayout.setVerticalGroup(
            jPanelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 121, Short.MAX_VALUE)
            .addGroup(jPanelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelFooterLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jButtonLeaveApp.setBackground(new java.awt.Color(99, 93, 255));
        jButtonLeaveApp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonLeaveApp.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLeaveApp.setText("LEAVE APPLICATION");
        jButtonLeaveApp.setMaximumSize(new java.awt.Dimension(200, 50));
        jButtonLeaveApp.setMinimumSize(new java.awt.Dimension(200, 50));
        jButtonLeaveApp.setPreferredSize(new java.awt.Dimension(200, 50));
        jButtonLeaveApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLeaveAppActionPerformed(evt);
            }
        });

        jButtonHome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonHome.setText("HOME");
        jButtonHome.setMaximumSize(new java.awt.Dimension(150, 50));
        jButtonHome.setMinimumSize(new java.awt.Dimension(150, 50));
        jButtonHome.setPreferredSize(new java.awt.Dimension(150, 50));
        jButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomeActionPerformed(evt);
            }
        });

        jButtonLogout.setBackground(new java.awt.Color(232, 19, 19));
        jButtonLogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonLogout.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLogout.setText("LOGOUT");
        jButtonLogout.setMaximumSize(new java.awt.Dimension(150, 50));
        jButtonLogout.setMinimumSize(new java.awt.Dimension(150, 50));
        jButtonLogout.setPreferredSize(new java.awt.Dimension(150, 50));
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });

        jButtonTimesheet.setBackground(new java.awt.Color(99, 93, 255));
        jButtonTimesheet.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonTimesheet.setForeground(new java.awt.Color(255, 255, 255));
        jButtonTimesheet.setText("TIMESHEET");
        jButtonTimesheet.setMaximumSize(new java.awt.Dimension(150, 50));
        jButtonTimesheet.setMinimumSize(new java.awt.Dimension(150, 50));
        jButtonTimesheet.setPreferredSize(new java.awt.Dimension(150, 50));
        jButtonTimesheet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTimesheetActionPerformed(evt);
            }
        });

        jButtonEmpInfo.setBackground(new java.awt.Color(99, 93, 255));
        jButtonEmpInfo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonEmpInfo.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEmpInfo.setText("EMPLOYEE INFORMATION");
        jButtonEmpInfo.setMaximumSize(new java.awt.Dimension(250, 50));
        jButtonEmpInfo.setMinimumSize(new java.awt.Dimension(250, 50));
        jButtonEmpInfo.setPreferredSize(new java.awt.Dimension(250, 50));
        jButtonEmpInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEmpInfoActionPerformed(evt);
            }
        });

        jButtonPayroll1.setBackground(new java.awt.Color(99, 93, 255));
        jButtonPayroll1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonPayroll1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPayroll1.setText("PAYROLL SUMMARY");
        jButtonPayroll1.setMaximumSize(new java.awt.Dimension(200, 50));
        jButtonPayroll1.setMinimumSize(new java.awt.Dimension(200, 50));
        jButtonPayroll1.setPreferredSize(new java.awt.Dimension(200, 50));
        jButtonPayroll1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPayroll1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelNavHomeLayout = new javax.swing.GroupLayout(jPanelNavHome);
        jPanelNavHome.setLayout(jPanelNavHomeLayout);
        jPanelNavHomeLayout.setHorizontalGroup(
            jPanelNavHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNavHomeLayout.createSequentialGroup()
                .addComponent(jButtonHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonTimesheet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonEmpInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPayroll1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLeaveApp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelNavHomeLayout.setVerticalGroup(
            jPanelNavHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNavHomeLayout.createSequentialGroup()
                .addGroup(jPanelNavHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLeaveApp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonTimesheet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEmpInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPayroll1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelEmpProfile.setBackground(new java.awt.Color(223, 227, 232));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Last Name:");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("First Name:");

        jTextField2FirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2FirstNameActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setText("Birthday:");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setText("Email:");

        jTextField3Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3EmailActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel23.setText("Designation:");

        jComboBox1Designation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Employee", "Admin" }));

        jButton8AddEmp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton8AddEmp.setText("Add");
        jButton8AddEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8AddEmpActionPerformed(evt);
            }
        });

        jButton9Update.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton9Update.setText("Update");
        jButton9Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9UpdateActionPerformed(evt);
            }
        });

        jButton11Clear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton11Clear.setText("Clear");
        jButton11Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ClearActionPerformed(evt);
            }
        });

        jLabel3EmpNo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3EmpNo.setText("Emp No.");

        jTextFieldEmpNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmpNoActionPerformed(evt);
            }
        });

        jLabel3Supervisor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3Supervisor.setText("Immediate Supervisor:");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel24.setText("Address: ");

        jLabelPhoneNo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelPhoneNo.setText("Phone No.:");

        jTextFieldPhoneNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPhoneNoActionPerformed(evt);
            }
        });

        jLabelSSS.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelSSS.setText("SSS:");

        jTextFieldSSS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSSSActionPerformed(evt);
            }
        });

        jLabelPhilHealth.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelPhilHealth.setText("Phil Health: ");

        jTextFieldPhilHealth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPhilHealthActionPerformed(evt);
            }
        });

        jLabelStatus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelStatus.setText("Employment Status:");

        jTextAreaAddress.setColumns(20);
        jTextAreaAddress.setRows(5);
        jScrollPane2.setViewportView(jTextAreaAddress);

        jLabelTIN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelTIN.setText("TIN #:");

        jTextFieldTIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTINActionPerformed(evt);
            }
        });

        jLabelPagIbig.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelPagIbig.setText("PAGIBIG #: ");

        jTextFieldPAGIBIG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPAGIBIGActionPerformed(evt);
            }
        });

        jButtonDelete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jLabel3Position.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3Position.setText("Employee Position: ");

        javax.swing.GroupLayout jPanelEmpProfileLayout = new javax.swing.GroupLayout(jPanelEmpProfile);
        jPanelEmpProfile.setLayout(jPanelEmpProfileLayout);
        jPanelEmpProfileLayout.setHorizontalGroup(
            jPanelEmpProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEmpProfileLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanelEmpProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEmpProfileLayout.createSequentialGroup()
                        .addComponent(jLabelPagIbig, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPAGIBIG, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelEmpProfileLayout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooser1Birthday, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelEmpProfileLayout.createSequentialGroup()
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEmpProfileLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelEmpProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEmpProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanelEmpProfileLayout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField1LastName, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelEmpProfileLayout.createSequentialGroup()
                        .addComponent(jLabel3EmpNo, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldEmpNo, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelEmpProfileLayout.createSequentialGroup()
                        .addComponent(jLabelPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabelSSS, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelEmpProfileLayout.createSequentialGroup()
                        .addComponent(jLabelPhilHealth, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPhilHealth, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jLabelTIN, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelEmpProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3Email, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSSS)
                    .addComponent(jTextFieldTIN))
                .addGap(26, 26, 26))
            .addGroup(jPanelEmpProfileLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEmpProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEmpProfileLayout.createSequentialGroup()
                        .addComponent(jLabel3Supervisor, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldSupervisor, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelEmpProfileLayout.createSequentialGroup()
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jComboBox1Designation, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelEmpProfileLayout.createSequentialGroup()
                        .addComponent(jButton8AddEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton9Update, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton11Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelEmpProfileLayout.createSequentialGroup()
                        .addComponent(jLabel3Position, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelEmpProfileLayout.setVerticalGroup(
            jPanelEmpProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEmpProfileLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEmpProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3EmpNo)
                    .addComponent(jTextFieldEmpNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelStatus)
                    .addComponent(jTextFieldStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEmpProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1LastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jTextField2FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEmpProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEmpProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel19)
                        .addComponent(jDateChooser1Birthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelEmpProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20)
                        .addComponent(jTextField3Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelEmpProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanelEmpProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEmpProfileLayout.createSequentialGroup()
                        .addGroup(jPanelEmpProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPhoneNo)
                            .addComponent(jTextFieldPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelSSS)
                            .addComponent(jTextFieldSSS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelEmpProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelPhilHealth)
                            .addComponent(jTextFieldPhilHealth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEmpProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldTIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelTIN)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEmpProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelPagIbig)
                    .addComponent(jTextFieldPAGIBIG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanelEmpProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3Position)
                    .addComponent(jTextFieldPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEmpProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3Supervisor)
                    .addComponent(jTextFieldSupervisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEmpProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1Designation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGap(18, 18, 18)
                .addGroup(jPanelEmpProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9Update)
                    .addComponent(jButton8AddEmp)
                    .addComponent(jButton11Clear)
                    .addComponent(jButtonDelete))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelSearch.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1Search.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1Search.setText("Search :");

        jTextField1Search.setMaximumSize(new java.awt.Dimension(64, 22));
        jTextField1Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1SearchActionPerformed(evt);
            }
        });
        jTextField1Search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1SearchKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1SearchKeyReleased(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Last Name", "First Name", "SSS No.", "PhilHealth", "TIN", "PAGIBIG"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButtonViewInformation.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonViewInformation.setText("View Information");
        jButtonViewInformation.setMaximumSize(new java.awt.Dimension(150, 22));
        jButtonViewInformation.setMinimumSize(new java.awt.Dimension(150, 22));
        jButtonViewInformation.setPreferredSize(new java.awt.Dimension(150, 22));
        jButtonViewInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewInformationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSearchLayout = new javax.swing.GroupLayout(jPanelSearch);
        jPanelSearch.setLayout(jPanelSearchLayout);
        jPanelSearchLayout.setHorizontalGroup(
            jPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanelSearchLayout.createSequentialGroup()
                        .addComponent(jLabel1Search, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1Search, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonViewInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 109, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelSearchLayout.setVerticalGroup(
            jPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonViewInformation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1Search, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField1Search, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFooter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelHeader, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelNavHome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelEmpProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelNavHome, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelEmpProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelFooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /* ############ CUSTOM CODE BELOW ############# */
    public void loadAllDataIntoTable(List<EmpDetails> list) {
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);
         SimpleDateFormat sdf = new SimpleDateFormat("MMMM-dd-yyyy");
         // JDM: Note that Vector class can be safely replaced with ArrayList
        for (EmpDetails eaLoadAllData : list) {
            Vector v = new Vector();
            v.add(eaLoadAllData.getId());
            v.add(eaLoadAllData.getLastName());
            v.add(eaLoadAllData.getFirstName());
            v.add(eaLoadAllData.getSSS());
            v.add(eaLoadAllData.getPhilHealth());
            v.add(eaLoadAllData.getTIN());
            v.add(eaLoadAllData.getPagIbig());

            dtm.addRow(v);
            
        }
    }
    
    
    public void loadTable (){
        DBConnection.loadConnection();
        EmpActions empActions = new EmpActions();
        List list =  empActions.loadData();
        loadAllDataIntoTable(list);
    }
    
    public void clearTextFieldsData(){
        jTextField1LastName.setText("");
        jTextField2FirstName.setText("");
        jDateChooser1Birthday.setDate(null);
        jTextField3Email.setText("");
        //jPasswordField1Password.setText("");
    }
    
     public void search(String str) {
        EmpActions eaSearch = new EmpActions();
        List<EmpDetails> list = eaSearch.searchEmployee(str);
        
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);

        for (EmpDetails edetail : list) {
            Object[] rowData = {
                edetail.getId(),
                edetail.getLastName(),
                edetail.getFirstName(),
                edetail.getSSS(),
                edetail.getPhilHealth(),
                edetail.getTIN(),
                edetail.getPagIbig()
            };
            dtm.addRow(rowData);
        }
    } 
    
    
    private void jButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonHomeActionPerformed

    private void jButtonLeaveAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLeaveAppActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLeaveAppActionPerformed

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        // TODO add your handling code here:
        JFrameLogin FrameLogin = new JFrameLogin();
        FrameLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonLogoutActionPerformed
    
    
    private void jButtonTimesheetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTimesheetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonTimesheetActionPerformed

    private void jButtonEmpInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEmpInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEmpInfoActionPerformed

    private void jTextField1SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1SearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1SearchActionPerformed

    private void jTextField1SearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1SearchKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1SearchKeyPressed

    private void jTextField1SearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1SearchKeyReleased
        String searchString = jTextField1Search.getText();
        search(searchString);
    }//GEN-LAST:event_jTextField1SearchKeyReleased

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int row = jTable1.getSelectedRow();
        if (row<0){
            JOptionPane.showMessageDialog(null,"Please select any record from table");
        }else{
            // Retrieve the Employee ID from the selected row
            id = (int) jTable1.getValueAt(row,0);
            EmpActions eactJTable = new EmpActions();
            EmpDetails eDetailsJTable = eactJTable.returnAllDataToTextField(id);
            jTextFieldEmpNo.setText(String.valueOf(eDetailsJTable.getId()));
            jTextFieldStatus.setText(eDetailsJTable.getSatus());
            jTextField1LastName.setText(eDetailsJTable.getLastName());
            jTextField2FirstName.setText(eDetailsJTable.getFirstName());
            jDateChooser1Birthday.setDate(eDetailsJTable.getBirthday());
            jTextField3Email.setText(eDetailsJTable.getEmail());
            jTextAreaAddress.setText(eDetailsJTable.getAddress());
            jTextFieldPhoneNo.setText(eDetailsJTable.getPhoneNumber());
            jTextFieldSSS.setText(eDetailsJTable.getSSS());
            jTextFieldPhilHealth.setText(eDetailsJTable.getPhilHealth());
            jTextFieldTIN.setText(eDetailsJTable.getTIN());
            jTextFieldPAGIBIG.setText(eDetailsJTable.getPagIbig());
            jTextFieldPosition.setText(eDetailsJTable.getPosition());
            jTextFieldSupervisor.setText(eDetailsJTable.getImmediateSupervisor());
            jComboBox1Designation.setSelectedItem(eDetailsJTable.getDesignation());

        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextField2FirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2FirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2FirstNameActionPerformed

    private void jTextField3EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3EmailActionPerformed

    private void jButton8AddEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8AddEmpActionPerformed

        String lastName = jTextField1LastName.getText();
        String firstName = jTextField2FirstName.getText();
        Date birthday = (Date) jDateChooser1Birthday.getDate();
        String email = jTextField3Email.getText();
        //String password = jPasswordField1Password.getText();
        String designation = (String) jComboBox1Designation.getSelectedItem();

        try {
            EmpDetails eDetailAdd = new EmpDetails(0, lastName, firstName, birthday, email, designation);

            EmpActions eActionAdd = new EmpActions();
            eActionAdd.insertDataAddEmp(eDetailAdd);
            loadTable();

            // Update the value of FirstLogin column to 1 for the newly added employee
            String query = "UPDATE motorphdb SET FirstLogin = 1 WHERE Email = ?";
            PreparedStatement ps = DBConnection.con.prepareStatement(query);
            ps.setString(1, email);
            ps.executeUpdate();

            // Show success message
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_jButton8AddEmpActionPerformed

    private void jButton9UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9UpdateActionPerformed

//        String lastName = jTextField1LastName.getText();
//        String firstName = jTextField2FirstName.getText();
//        Date birthday = (Date) jDateChooser1Birthday.getDate();
//        String email = jTextField3Email.getText();
//        //String password = jPasswordField1Password.getText();
//        String designation = (String)jComboBox1Designation.getSelectedItem();



	String lastName = jTextField1LastName.getText();
	String firstName = jTextField2FirstName.getText();
	Date birthday = (Date) jDateChooser1Birthday.getDate();
	String email = jTextField3Email.getText();
	String designation = (String)jComboBox1Designation.getSelectedItem();                
        
	String address = jTextAreaAddress.getText();
	String PhoneNo = jTextFieldPhoneNo.getText();
	String SSSNo = jTextFieldSSS.getText();
	String philHealth = jTextFieldPhilHealth.getText();
	String tinNo = jTextFieldTIN.getText();
	
        String pagibigNo = jTextFieldPAGIBIG.getText();
	String EmpStatus = jTextFieldStatus.getText();
        String position = jTextFieldPosition.getText();
	String supervisor = jTextFieldSupervisor.getText();
	Integer EmpID = Integer.parseInt(jTextFieldEmpNo.getText());        

        EmpDetails edUpdate = new EmpDetails(EmpID,
        lastName,        firstName,        birthday,        email,        designation,                address,        
        PhoneNo,        SSSNo,        philHealth,        tinNo,        pagibigNo,        EmpStatus,        position,
        supervisor);
        EmpActions eaUpdate = new EmpActions();
        eaUpdate.updateEmpDetails(edUpdate);
        loadTable();

    }//GEN-LAST:event_jButton9UpdateActionPerformed

    private void jButton11ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ClearActionPerformed
        clearTextFieldsData();
    }//GEN-LAST:event_jButton11ClearActionPerformed

    private void jButtonPayroll1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPayroll1ActionPerformed
        new JFrameEmpPayroll().setVisible(true);
    }//GEN-LAST:event_jButtonPayroll1ActionPerformed

    private void jTextFieldPhoneNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPhoneNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPhoneNoActionPerformed

    private void jTextFieldSSSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSSSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSSSActionPerformed

    private void jTextFieldPhilHealthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPhilHealthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPhilHealthActionPerformed

    private void jTextFieldTINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTINActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTINActionPerformed

    private void jTextFieldPAGIBIGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPAGIBIGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPAGIBIGActionPerformed

    private void jTextFieldEmpNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmpNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmpNoActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonViewInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewInformationActionPerformed
        new JFrameEmpPayroll().setVisible(true);
        
        new JFrameSelectMonthYear().setVisible(true);
        this.dispose();
    
    }//GEN-LAST:event_jButtonViewInformationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameEmpInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameEmpInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameEmpInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameEmpInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameEmpInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton11Clear;
    private javax.swing.JButton jButton8AddEmp;
    private javax.swing.JButton jButton9Update;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonEmpInfo;
    private javax.swing.JButton jButtonHome;
    private javax.swing.JButton jButtonLeaveApp;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonPayroll1;
    private javax.swing.JButton jButtonTimesheet;
    private javax.swing.JButton jButtonViewInformation;
    private javax.swing.JComboBox<String> jComboBox1Designation;
    private com.toedter.calendar.JDateChooser jDateChooser1Birthday;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel1Search;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3EmpNo;
    private javax.swing.JLabel jLabel3Position;
    private javax.swing.JLabel jLabel3Supervisor;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelPagIbig;
    private javax.swing.JLabel jLabelPhilHealth;
    private javax.swing.JLabel jLabelPhoneNo;
    private javax.swing.JLabel jLabelSSS;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JLabel jLabelTIN;
    private javax.swing.JPanel jPanelEmpProfile;
    private javax.swing.JPanel jPanelFooter;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel jPanelNavHome;
    private javax.swing.JPanel jPanelSearch;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextAreaAddress;
    private javax.swing.JTextField jTextField1LastName;
    private javax.swing.JTextField jTextField1Search;
    private javax.swing.JTextField jTextField2FirstName;
    private javax.swing.JTextField jTextField3Email;
    private javax.swing.JTextField jTextFieldEmpNo;
    private javax.swing.JTextField jTextFieldPAGIBIG;
    private javax.swing.JTextField jTextFieldPhilHealth;
    private javax.swing.JTextField jTextFieldPhoneNo;
    private javax.swing.JTextField jTextFieldPosition;
    private javax.swing.JTextField jTextFieldSSS;
    private javax.swing.JTextField jTextFieldStatus;
    private javax.swing.JTextField jTextFieldSupervisor;
    private javax.swing.JTextField jTextFieldTIN;
    private java.awt.Label labelCompany;
    private javax.swing.JLabel labelLogo;
    // End of variables declaration//GEN-END:variables
}
