/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.screens;

import DBConnection.DBConnection;
import com.baseActions.EmpActions;
import com.baseActions.EmpDetails;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import javax.swing.JTextField;

/**
 *
 * @author CHAS
 */
public final class JFrameEmpPayroll extends javax.swing.JFrame {

    
    public static JFrameEmpPayroll Instance;
    public JTextField empNo;
    
    /**
     * Creates new form JFrameEmpPayroll
     */

    public JFrameEmpPayroll() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setResizable(false);
        Instance = this;
        empNo = jTextFieldEmp;
        
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelHeader = new javax.swing.JPanel();
        labelCompany = new java.awt.Label();
        labelLogo = new javax.swing.JLabel();
        jPanelFooter = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanelNavHome = new javax.swing.JPanel();
        jButtonLeaveApp = new javax.swing.JButton();
        jButtonHome = new javax.swing.JButton();
        jButtonLogout = new javax.swing.JButton();
        jButtonTimesheet = new javax.swing.JButton();
        jButtonEmpInfo = new javax.swing.JButton();
        jButtonPayroll1 = new javax.swing.JButton();
        JPanelEmpInfo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldEmp = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        FldStatus = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        FldLastName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        FldTin = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        FldPosition = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        FldSupervisor = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        FldBirthday = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        FldSSS = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        FldFirstName = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        FldPhoneNumber = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        FldPhilhealth = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        FldPagibig = new javax.swing.JTextField();
        jPanelPayInfo = new javax.swing.JPanel();
        BtnCompute = new javax.swing.JButton();
        jPanelMonth = new javax.swing.JPanel();
        jLabelMonth = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jPanelTimeSheet = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabelUndertime = new javax.swing.JLabel();
        jLabelOvertime = new javax.swing.JLabel();
        jLabelHWorked = new javax.swing.JLabel();
        jLabelTHWorked = new javax.swing.JLabel();
        jPanelDeductions = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabelSSS = new javax.swing.JLabel();
        jLabelTIN = new javax.swing.JLabel();
        jLabelPhilhealth = new javax.swing.JLabel();
        jLabelPagibig = new javax.swing.JLabel();
        jPanelSalary = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabelBasic = new javax.swing.JLabel();
        jLabelGross = new javax.swing.JLabel();
        jLabelDeductions = new javax.swing.JLabel();
        jLabelNet = new javax.swing.JLabel();
        jLabelMonth1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1080, 720));

        jPanelHeader.setBackground(new java.awt.Color(99, 93, 255));

        labelCompany.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        labelCompany.setForeground(new java.awt.Color(255, 255, 255));
        labelCompany.setText("MotorPH");

        labelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LOGO_icon.png"))); // NOI18N
        labelLogo.setText("jLabel1");
        labelLogo.setMaximumSize(new java.awt.Dimension(172, 119));
        labelLogo.setMinimumSize(new java.awt.Dimension(172, 119));
        labelLogo.setPreferredSize(new java.awt.Dimension(172, 192));

        javax.swing.GroupLayout jPanelHeaderLayout = new javax.swing.GroupLayout(jPanelHeader);
        jPanelHeader.setLayout(jPanelHeaderLayout);
        jPanelHeaderLayout.setHorizontalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1224, Short.MAX_VALUE))
        );
        jPanelHeaderLayout.setVerticalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addGroup(jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelHeaderLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelHeaderLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(labelCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelFooter.setBackground(new java.awt.Color(99, 93, 255));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Office Hours: 8:00AM - 5:00PM");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Office Address: 5th Flr., The World Center #330 Sen. Gil Puyat Ave., Makati City, Manila, Philippines");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Office Phone Number: +63-2-754-7000");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Office Email: support@motorph.com");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Group 1");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Section : A1101");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("MO-IT103 - Computer Programming 2");

        javax.swing.GroupLayout jPanelFooterLayout = new javax.swing.GroupLayout(jPanelFooter);
        jPanelFooter.setLayout(jPanelFooterLayout);
        jPanelFooterLayout.setHorizontalGroup(
            jPanelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelFooterLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addGroup(jPanelFooterLayout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(396, 396, 396)
                            .addComponent(jLabel11))
                        .addGroup(jPanelFooterLayout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(687, 687, 687)
                            .addComponent(jLabel21))
                        .addGroup(jPanelFooterLayout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(574, 574, 574)
                            .addComponent(jLabel18)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelFooterLayout.setVerticalGroup(
            jPanelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 121, Short.MAX_VALUE)
            .addGroup(jPanelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelFooterLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jButtonLeaveApp.setBackground(new java.awt.Color(99, 93, 255));
        jButtonLeaveApp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonLeaveApp.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLeaveApp.setText("LEAVE APPLICATION");
        jButtonLeaveApp.setMaximumSize(new java.awt.Dimension(200, 50));
        jButtonLeaveApp.setMinimumSize(new java.awt.Dimension(200, 50));
        jButtonLeaveApp.setPreferredSize(new java.awt.Dimension(200, 50));
        jButtonLeaveApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLeaveAppActionPerformed(evt);
            }
        });

        jButtonHome.setBackground(new java.awt.Color(99, 93, 255));
        jButtonHome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonHome.setForeground(new java.awt.Color(255, 255, 255));
        jButtonHome.setText("HOME");
        jButtonHome.setMaximumSize(new java.awt.Dimension(150, 50));
        jButtonHome.setMinimumSize(new java.awt.Dimension(150, 50));
        jButtonHome.setPreferredSize(new java.awt.Dimension(150, 50));
        jButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomeActionPerformed(evt);
            }
        });

        jButtonLogout.setBackground(new java.awt.Color(232, 19, 19));
        jButtonLogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonLogout.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLogout.setText("LOGOUT");
        jButtonLogout.setMaximumSize(new java.awt.Dimension(150, 50));
        jButtonLogout.setMinimumSize(new java.awt.Dimension(150, 50));
        jButtonLogout.setPreferredSize(new java.awt.Dimension(150, 50));
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });

        jButtonTimesheet.setBackground(new java.awt.Color(99, 93, 255));
        jButtonTimesheet.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonTimesheet.setForeground(new java.awt.Color(255, 255, 255));
        jButtonTimesheet.setText("TIMESHEET");
        jButtonTimesheet.setMaximumSize(new java.awt.Dimension(150, 50));
        jButtonTimesheet.setMinimumSize(new java.awt.Dimension(150, 50));
        jButtonTimesheet.setPreferredSize(new java.awt.Dimension(150, 50));
        jButtonTimesheet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTimesheetActionPerformed(evt);
            }
        });

        jButtonEmpInfo.setBackground(new java.awt.Color(99, 93, 255));
        jButtonEmpInfo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonEmpInfo.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEmpInfo.setText("EMPLOYEE INFORMATION");
        jButtonEmpInfo.setMaximumSize(new java.awt.Dimension(250, 50));
        jButtonEmpInfo.setMinimumSize(new java.awt.Dimension(250, 50));
        jButtonEmpInfo.setPreferredSize(new java.awt.Dimension(250, 50));
        jButtonEmpInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEmpInfoActionPerformed(evt);
            }
        });

        jButtonPayroll1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonPayroll1.setText("PAYROLL SUMMARY");
        jButtonPayroll1.setMaximumSize(new java.awt.Dimension(200, 50));
        jButtonPayroll1.setMinimumSize(new java.awt.Dimension(200, 50));
        jButtonPayroll1.setPreferredSize(new java.awt.Dimension(200, 50));
        jButtonPayroll1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPayroll1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelNavHomeLayout = new javax.swing.GroupLayout(jPanelNavHome);
        jPanelNavHome.setLayout(jPanelNavHomeLayout);
        jPanelNavHomeLayout.setHorizontalGroup(
            jPanelNavHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNavHomeLayout.createSequentialGroup()
                .addComponent(jButtonHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonTimesheet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonEmpInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPayroll1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLeaveApp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelNavHomeLayout.setVerticalGroup(
            jPanelNavHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNavHomeLayout.createSequentialGroup()
                .addGroup(jPanelNavHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLeaveApp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonTimesheet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEmpInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPayroll1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JPanelEmpInfo.setBackground(new java.awt.Color(223, 227, 232));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Emp No:");

        jTextFieldEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmpActionPerformed(evt);
            }
        });
        jTextFieldEmp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldEmpKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Status:");

        FldStatus.setEditable(false);
        FldStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FldStatusActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Last Name:");

        FldLastName.setEditable(false);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("First Name:");

        FldTin.setEditable(false);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Position:");

        FldPosition.setEditable(false);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Immediate Supervisor");

        FldSupervisor.setEditable(false);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Birthday:");

        FldBirthday.setEditable(false);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("SSS #:");

        FldSSS.setEditable(false);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("Phone Number:");

        FldFirstName.setEditable(false);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("TIN #:");

        FldPhoneNumber.setEditable(false);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("Philhealth #:");

        FldPhilhealth.setEditable(false);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("Pag-Ibig #:");

        FldPagibig.setEditable(false);

        javax.swing.GroupLayout JPanelEmpInfoLayout = new javax.swing.GroupLayout(JPanelEmpInfo);
        JPanelEmpInfo.setLayout(JPanelEmpInfoLayout);
        JPanelEmpInfoLayout.setHorizontalGroup(
            JPanelEmpInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelEmpInfoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(JPanelEmpInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPanelEmpInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FldSupervisor)
                    .addComponent(FldPosition)
                    .addGroup(JPanelEmpInfoLayout.createSequentialGroup()
                        .addGroup(JPanelEmpInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JPanelEmpInfoLayout.createSequentialGroup()
                                .addGroup(JPanelEmpInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39)
                                .addGroup(JPanelEmpInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(JPanelEmpInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FldStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(JPanelEmpInfoLayout.createSequentialGroup()
                                .addGroup(JPanelEmpInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(FldBirthday, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FldSSS, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(FldPhilhealth, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addGroup(JPanelEmpInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel17))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(JPanelEmpInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FldTin, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FldPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FldPagibig, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18))
        );
        JPanelEmpInfoLayout.setVerticalGroup(
            JPanelEmpInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelEmpInfoLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(JPanelEmpInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(FldStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JPanelEmpInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(FldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(FldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JPanelEmpInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(FldPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JPanelEmpInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(FldSupervisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JPanelEmpInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(FldBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(FldPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JPanelEmpInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(FldSSS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(FldTin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JPanelEmpInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(FldPhilhealth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(FldPagibig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BtnCompute.setBackground(new java.awt.Color(99, 93, 255));
        BtnCompute.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnCompute.setForeground(new java.awt.Color(255, 255, 255));
        BtnCompute.setText("COMPUTE");

        jLabelMonth.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelMonth.setText("MONTH:");

        jComboBox2.setBackground(new java.awt.Color(99, 93, 255));
        jComboBox2.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January ", "February ", "March ", "April ", "May ", "June ", "July ", "August ", "September ", "October ", "November ", "December " }));

        javax.swing.GroupLayout jPanelMonthLayout = new javax.swing.GroupLayout(jPanelMonth);
        jPanelMonth.setLayout(jPanelMonthLayout);
        jPanelMonthLayout.setHorizontalGroup(
            jPanelMonthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMonthLayout.createSequentialGroup()
                .addComponent(jLabelMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
            .addGroup(jPanelMonthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMonthLayout.createSequentialGroup()
                    .addContainerGap(108, Short.MAX_VALUE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)))
        );
        jPanelMonthLayout.setVerticalGroup(
            jPanelMonthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMonthLayout.createSequentialGroup()
                .addComponent(jLabelMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
            .addGroup(jPanelMonthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelMonthLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanelTimeSheet.setPreferredSize(new java.awt.Dimension(500, 400));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setText("Employee Timesheet:");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel22.setText("Undertime:");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel24.setText("Overtime:");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel25.setText("Hours Worked:");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel23.setText("Total Hours Worked:");

        jLabelUndertime.setText("test");

        jLabelOvertime.setText("test");

        jLabelHWorked.setText("test");

        jLabelTHWorked.setText("test");

        javax.swing.GroupLayout jPanelTimeSheetLayout = new javax.swing.GroupLayout(jPanelTimeSheet);
        jPanelTimeSheet.setLayout(jPanelTimeSheetLayout);
        jPanelTimeSheetLayout.setHorizontalGroup(
            jPanelTimeSheetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTimeSheetLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanelTimeSheetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addGroup(jPanelTimeSheetLayout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addGroup(jPanelTimeSheetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelTimeSheetLayout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelUndertime))
                            .addGroup(jPanelTimeSheetLayout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelOvertime))
                            .addGroup(jPanelTimeSheetLayout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                                .addComponent(jLabelTHWorked))
                            .addGroup(jPanelTimeSheetLayout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelHWorked)))))
                .addGap(64, 64, 64))
        );
        jPanelTimeSheetLayout.setVerticalGroup(
            jPanelTimeSheetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTimeSheetLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addGroup(jPanelTimeSheetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabelUndertime))
                .addGap(18, 18, 18)
                .addGroup(jPanelTimeSheetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jLabelOvertime))
                .addGap(18, 18, 18)
                .addGroup(jPanelTimeSheetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jLabelHWorked))
                .addGap(18, 18, 18)
                .addGroup(jPanelTimeSheetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jLabelTHWorked))
                .addContainerGap(166, Short.MAX_VALUE))
        );

        jPanelDeductions.setPreferredSize(new java.awt.Dimension(500, 400));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel26.setText("Deductions:");

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel27.setText("SSS:");

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel28.setText("TIN:");

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel29.setText("Philhealth:");

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel30.setText("Pag-Ibig:");

        jLabelSSS.setText("test");

        jLabelTIN.setText("test");

        jLabelPhilhealth.setText("test");

        jLabelPagibig.setText("test");

        javax.swing.GroupLayout jPanelDeductionsLayout = new javax.swing.GroupLayout(jPanelDeductions);
        jPanelDeductions.setLayout(jPanelDeductionsLayout);
        jPanelDeductionsLayout.setHorizontalGroup(
            jPanelDeductionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDeductionsLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanelDeductionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addGroup(jPanelDeductionsLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(jPanelDeductionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelDeductionsLayout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelTIN))
                            .addGroup(jPanelDeductionsLayout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelSSS))
                            .addGroup(jPanelDeductionsLayout.createSequentialGroup()
                                .addComponent(jLabel30)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelPagibig))
                            .addGroup(jPanelDeductionsLayout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 226, Short.MAX_VALUE)
                                .addComponent(jLabelPhilhealth)))))
                .addGap(61, 61, 61))
        );
        jPanelDeductionsLayout.setVerticalGroup(
            jPanelDeductionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDeductionsLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jLabel26)
                .addGap(18, 18, 18)
                .addGroup(jPanelDeductionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jLabelSSS))
                .addGap(18, 18, 18)
                .addGroup(jPanelDeductionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jLabelTIN))
                .addGap(24, 24, 24)
                .addGroup(jPanelDeductionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jLabelPhilhealth))
                .addGap(18, 18, 18)
                .addGroup(jPanelDeductionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(jLabelPagibig))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelSalary.setPreferredSize(new java.awt.Dimension(500, 400));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel31.setText("Monthly Salary:");

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel32.setText("Basic Salary:");

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel33.setText("Gross Salary:");

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel34.setText("Total Deductions:");

        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel35.setText("Net Salary:");

        jLabelBasic.setText("test");

        jLabelGross.setText("test");

        jLabelDeductions.setText("test");

        jLabelNet.setText("test");

        javax.swing.GroupLayout jPanelSalaryLayout = new javax.swing.GroupLayout(jPanelSalary);
        jPanelSalary.setLayout(jPanelSalaryLayout);
        jPanelSalaryLayout.setHorizontalGroup(
            jPanelSalaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSalaryLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(jPanelSalaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSalaryLayout.createSequentialGroup()
                        .addGroup(jPanelSalaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel31)
                            .addComponent(jLabel32)
                            .addComponent(jLabel33))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                        .addGroup(jPanelSalaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelBasic)
                            .addComponent(jLabelGross)
                            .addComponent(jLabelDeductions)))
                    .addGroup(jPanelSalaryLayout.createSequentialGroup()
                        .addGroup(jPanelSalaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel34)
                            .addComponent(jLabel35, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelNet)))
                .addGap(95, 95, 95))
        );
        jPanelSalaryLayout.setVerticalGroup(
            jPanelSalaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSalaryLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(jPanelSalaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSalaryLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanelSalaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel32)
                            .addComponent(jLabelBasic)))
                    .addComponent(jLabel31))
                .addGap(18, 18, 18)
                .addGroup(jPanelSalaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel33)
                    .addComponent(jLabelGross))
                .addGap(18, 18, 18)
                .addGroup(jPanelSalaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel34)
                    .addComponent(jLabelDeductions))
                .addGap(18, 18, 18)
                .addGroup(jPanelSalaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel35)
                    .addComponent(jLabelNet))
                .addContainerGap(151, Short.MAX_VALUE))
        );

        jLabelMonth1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelMonth1.setText("YEAR:");

        jComboBox1.setBackground(new java.awt.Color(99, 93, 255));
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2022", "2023", "2024" }));

        javax.swing.GroupLayout jPanelPayInfoLayout = new javax.swing.GroupLayout(jPanelPayInfo);
        jPanelPayInfo.setLayout(jPanelPayInfoLayout);
        jPanelPayInfoLayout.setHorizontalGroup(
            jPanelPayInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPayInfoLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanelPayInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelTimeSheet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelDeductions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelPayInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPayInfoLayout.createSequentialGroup()
                        .addGap(351, 351, 351)
                        .addComponent(BtnCompute)
                        .addGap(105, 105, 105))
                    .addGroup(jPanelPayInfoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanelPayInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelSalary, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPayInfoLayout.createSequentialGroup()
                                .addGroup(jPanelPayInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelPayInfoLayout.createSequentialGroup()
                                        .addComponent(jLabelMonth1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jPanelMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)))
                        .addContainerGap())))
        );
        jPanelPayInfoLayout.setVerticalGroup(
            jPanelPayInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPayInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelTimeSheet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelDeductions, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanelPayInfoLayout.createSequentialGroup()
                .addComponent(jPanelMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPayInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMonth1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(103, 103, 103)
                .addComponent(jPanelSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 189, Short.MAX_VALUE)
                .addComponent(BtnCompute)
                .addGap(166, 166, 166))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JPanelEmpInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelPayInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(6, 6, 6))
                    .addComponent(jPanelNavHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelFooter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(jPanelNavHome, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JPanelEmpInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelPayInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelFooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1135, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void search(String str) {
        EmpActions eaSearch = new EmpActions();
        List<EmpDetails> list = (List<EmpDetails>) eaSearch.searchEmployee(str);
        
       for(EmpDetails edetail : list){
         FldLastName.setText(edetail.getLastName());
         FldStatus.setText(edetail.getSatus());
         FldFirstName.setText(edetail.getFirstName());
         FldPosition.setText(edetail.getPosition());
         FldSupervisor.setText(edetail.getImmediateSupervisor());
         // FldBirthday.setDate(edetail.getBirthday()); //getting error when accessing setDate
         FldPhoneNumber.setText(edetail.getPhoneNumber());
         FldSSS.setText(edetail.getSSS());
         FldTin.setText(edetail.getTIN());
         FldPhilhealth.setText(edetail.getPhilHealth());
         FldPagibig.setText(edetail.getPagIbig());
         
        }
    } 
   
    private void jButtonLeaveAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLeaveAppActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLeaveAppActionPerformed

    private void jButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomeActionPerformed
        // TODO add your handling code here:
        JFrameHome frameHome = new JFrameHome();
        frameHome.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonHomeActionPerformed

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        // TODO add your handling code here:
        JFrameLogin FrameLogin = new JFrameLogin();
        FrameLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonLogoutActionPerformed

    private void jButtonTimesheetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTimesheetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonTimesheetActionPerformed

    private void jButtonEmpInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEmpInfoActionPerformed
        // TODO add your handling code here:
        JFrameEmpInfo frameEmpInfo = new JFrameEmpInfo();
        frameEmpInfo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonEmpInfoActionPerformed

    private void jButtonPayroll1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPayroll1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPayroll1ActionPerformed

    private void FldStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FldStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FldStatusActionPerformed

    private void jTextFieldEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmpActionPerformed

    private void jTextFieldEmpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEmpKeyReleased
        // TODO add your handling code here:
        String searchString = jTextFieldEmp.getText();
        search(searchString);
    }//GEN-LAST:event_jTextFieldEmpKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameEmpPayroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameEmpPayroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameEmpPayroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameEmpPayroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameEmpPayroll().setVisible(true);
              
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCompute;
    private javax.swing.JTextField FldBirthday;
    private javax.swing.JTextField FldFirstName;
    private javax.swing.JTextField FldLastName;
    private javax.swing.JTextField FldPagibig;
    private javax.swing.JTextField FldPhilhealth;
    private javax.swing.JTextField FldPhoneNumber;
    private javax.swing.JTextField FldPosition;
    private javax.swing.JTextField FldSSS;
    private javax.swing.JTextField FldStatus;
    private javax.swing.JTextField FldSupervisor;
    private javax.swing.JTextField FldTin;
    private javax.swing.JPanel JPanelEmpInfo;
    private javax.swing.JButton jButtonEmpInfo;
    private javax.swing.JButton jButtonHome;
    private javax.swing.JButton jButtonLeaveApp;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonPayroll1;
    private javax.swing.JButton jButtonTimesheet;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelBasic;
    private javax.swing.JLabel jLabelDeductions;
    private javax.swing.JLabel jLabelGross;
    private javax.swing.JLabel jLabelHWorked;
    private javax.swing.JLabel jLabelMonth;
    private javax.swing.JLabel jLabelMonth1;
    private javax.swing.JLabel jLabelNet;
    private javax.swing.JLabel jLabelOvertime;
    private javax.swing.JLabel jLabelPagibig;
    private javax.swing.JLabel jLabelPhilhealth;
    private javax.swing.JLabel jLabelSSS;
    private javax.swing.JLabel jLabelTHWorked;
    private javax.swing.JLabel jLabelTIN;
    private javax.swing.JLabel jLabelUndertime;
    private javax.swing.JPanel jPanelDeductions;
    private javax.swing.JPanel jPanelFooter;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel jPanelMonth;
    private javax.swing.JPanel jPanelNavHome;
    private javax.swing.JPanel jPanelPayInfo;
    private javax.swing.JPanel jPanelSalary;
    private javax.swing.JPanel jPanelTimeSheet;
    private javax.swing.JTextField jTextFieldEmp;
    private java.awt.Label labelCompany;
    private javax.swing.JLabel labelLogo;
    // End of variables declaration//GEN-END:variables
}
